# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170331_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='town',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
