# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170402_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='image',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic'),
        ),
    ]
