# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170423_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='profilepic',
        ),
    ]
